# this rule used for setting a component data/equation names
# component name:
# DATA:
#   data symbol defined in TableData: new symbol
# EQUATIONS:
#   equation symbol defined in TableEquations: new symbol

ALL:
  DATA:
    Pc: Pc
    Tc: Tc
    AcFa: AcFa
    enthalpy-of-formation-ideal-gas: EnFo_IG
    gibbs-energy-of-formation-ideal-gas: GiEnFo_IG
    enthalpy-of-formation-liquid: EnFo_LIQ
    gibbs-energy-of-formation-liquid: GiEnFo_LIQ
    boiling-temperature: Tb
    melting-temperature: Tm
    sublimation-temperature: Ts
  EQUATIONS:
    vapor-pressure: VaPr
    ideal-gas-heat-capacity: Cp_IG
    liquid-heat-capacity: Cp_LIQ
    enthalpy-of-vaporization: EnVap
    enthalpy-of-fusion: EnFus
    enthalpy-of-sublimation: EnSub